---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
# BiomassWorkflow

An R package that is helpful in streamlining data analysis and removing the potential for errors in the process. The package is most useful for generating biomass data and comparing biomass between various groups. There are also a couple of helper functions included and other scripts that help with moving samples through the processing pipeline.

The package can be downloaded from within R using the devtools function:

```R
  devtools::install_github("econtijoch/Biomass-Workflow")
```

If you need to install devtools first, you'll need to do the following first to download and update devtools to the most current version:

```R
	install.packages("devtools")
	devtools::install_github("hadley/devtools")
```

<p>Each of the functions has its own documentation that can further explain their usage, and I have developed vignettes for walking through most of the features of the package.</p>



