#' Color Scheme function for plotting
#' @export
#'

EJC_colors <- rep(c("#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999", "#E69F00", "red", "blue", 
    "magenta", "purple", "cyan", "yellow", "navyblue", "tan", "seagreen", "green", "goldenrod", "antiquewhite3", "darkolivegreen", 
    "brown", "deeppink3"), 100)


#' Color Scheme function for phyla
#' @export
#'

phyla_colors <- setNames(object = c('#56B4E9', '#009E73', '#F0E442', '#0072B2', '#D55E00', '#CC79A7', '#999999', '#E69F00', 'red', 'blue', 'magenta', 'purple', 'cyan', 'yellow', 'navyblue', 'tan', 'seagreen', 'green', 'goldenrod', 'antiquewhite3', 'darkolivegreen', 'brown', 'deeppink3', '#56B4E9', '#009E73', '#F0E442', '#0072B2', '#D55E00', '#CC79A7', '#999999', '#E69F00', 'red', 'blue', 'magenta', 'purple', 'cyan', 'yellow', 'navyblue', 'tan', 'seagreen', 'green', 'goldenrod', 'antiquewhite3', 'darkolivegreen', 'brown', 'deeppink3', '#56B4E9', '#009E73', '#F0E442', '#0072B2', '#D55E00', '#CC79A7', '#999999', '#E69F00', 'red', 'blue', 'magenta', 'purple', 'cyan', 'yellow', 'navyblue', 'tan', 'seagreen', 'green', 'goldenrod', 'antiquewhite3', 'darkolivegreen', 'brown', 'deeppink3', '#56B4E9', '#009E73', '#F0E442', '#0072B2', '#D55E00', '#CC79A7', '#999999', '#E69F00', 'red', 'blue', 'magenta', 'purple', 'cyan', 'yellow', 'navyblue', 'tan', 'seagreen', 'green', 'goldenrod', 'antiquewhite3', 'darkolivegreen'),
                         nm = c('Bacteria__Bacteroidetes', 'Bacteria__Firmicutes', 'Bacteria__Cyanobacteria', 'Bacteria__Proteobacteria', 'Bacteria__Acidobacteria', 'Bacteria__Verrucomicrobia', 'Bacteria__Spirochaetes', 'Bacteria__[[unclassified]]', 'Bacteria__Actinobacteria', 'Bacteria__Planctomycetes', 'Bacteria__Tenericutes', 'Bacteria__Chloroflexi', 'Bacteria__Euryarchaeota', 'Bacteria__Crenarchaeota', 'Bacteria__TM7', 'Bacteria__Armatimonadetes', 'Bacteria__Chlorobi', 'Bacteria__GN04', 'Bacteria__NKB19', 'Bacteria__Synergistetes', 'Bacteria__Fibrobacteres', 'Bacteria__Fusobacteria', 'Bacteria__WWE1', 'Bacteria__Nitrospirae', 'Bacteria__Lentisphaerae', 'Bacteria__GN02', 'Bacteria__WS2', 'Bacteria__WPS-2', 'Bacteria__Gemmatimonadetes', 'Bacteria__OP11', 'Bacteria__WS6', 'Bacteria__OP9', 'Bacteria__OD1', 'Bacteria__WS3', 'Bacteria__OP8', 'Bacteria__MAT-CR-M4-B07', 'Bacteria__TM6', 'Bacteria__[Caldithrix]', 'Bacteria__Aquificae', 'Bacteria__SAR406', 'Bacteria__OP3', 'Bacteria__[Thermi]', 'Bacteria__LD1', 'Bacteria__AD3', 'Bacteria__KSB3', 'Bacteria__Elusimicrobia', 'Bacteria__Caldiserica', 'Bacteria__BRC1', 'Bacteria__FBP', 'Bacteria__EM3', 'Bacteria__Hyd24-12', 'Bacteria__[Parvarchaeota]', 'Bacteria__NC10', 'Bacteria__SBR1093', 'Bacteria__OP1', 'Bacteria__AC1', 'Bacteria__BHI80-139', 'Bacteria__TPD-58', 'Bacteria__Thermotogae', 'Bacteria__GN01', 'Bacteria__WS1', 'Bacteria__Chrysiogenetes', 'Bacteria__GOUTA4', 'Bacteria__AncK6', 'Bacteria__PAUC34f', 'Bacteria__SR1', 'Bacteria__CD12', 'Bacteria__Chlamydiae', 'Bacteria__GAL15', 'Bacteria__Kazan-3B-28', 'Bacteria__ZB3', 'Bacteria__Deferribacteres', 'Bacteria__FCPU426', 'Bacteria__H-178', 'Bacteria__Nanoarchaeota', 'Bacteria__Caldithrix', 'Bacteria__NPL-UPA2', 'Bacteria__VHS-B3-43', 'Bacteria__Poribacteria', 'Bacteria__LCP-89', 'Bacteria__WS5', 'Bacteria__MVP-21', 'Bacteria__Dictyoglomi', 'Bacteria__SC4', 'Bacteria__MVS-104', 'Bacteria__WS4', 'Bacteria__OctSpA1-106', 'Bacteria__OC31', 'Bacteria__TA06', 'Bacteria__EM19'))

